export const ARTICLE_COVER_LABEL = '文章封面'

export const ARTICLE_COVER_ASPECT_RATIO = '16:10'
export const ARTICLE_COVER_RECOMMENDED_SIZE = '1600×1000 px'
export const ARTICLE_COVER_ALTERNATIVE_SIZES = '1280×800、1920×1200'
export const ARTICLE_COVER_FORMATS = 'JPG、PNG、WebP'
export const ARTICLE_COVER_MAX_SIZE = '0.3MB'

export const ARTICLE_COVER_SPEC_EXTRA =
  `博客列表与推荐位以 ${ARTICLE_COVER_ASPECT_RATIO} 展示封面，建议上传 ${ARTICLE_COVER_ASPECT_RATIO} 比例以避免前台留白。`
  + ` 推荐尺寸 ${ARTICLE_COVER_RECOMMENDED_SIZE}（备选 ${ARTICLE_COVER_ALTERNATIVE_SIZES}），`
  + `支持 ${ARTICLE_COVER_FORMATS}，压缩后 ≤ ${ARTICLE_COVER_MAX_SIZE}。`
