export default interface WebsiteInfo {
    webmasterAvatar: string;
    webmasterName: string;
    webmasterCopy: string;
    webmasterProfileBackground: string;
    giteeLink: string;
    githubLink: string;
    websiteName: string;
    heroKicker?: string;
    heroTitle?: string;
    heroSubtitle?: string;
    heroDescription?: string;
    heroPrimaryText?: string;
    heroPrimaryUrl?: string;
    heroSecondaryText?: string;
    heroSecondaryUrl?: string;
    heroAsideLabel?: string;
    heroAsideText?: string;
    headerNotification: string;
    sidebarAnnouncement: string;
    recordInfo: string;
    startTime: string;
    lastUpdateTime: string;
    articleCount: number;
    categoryCount: number;
    commentCount: number;
    wordCount: number;
    visitCount: number;
}
